-- Customers
INSERT INTO CUSTOMERS (ID, NAME, EMAIL) VALUES (11, 'John Doe', 'john@example.com');
INSERT INTO CUSTOMERS (ID, NAME, EMAIL) VALUES (12, 'Jane Smith', 'jane@example.com');

-- Orders
INSERT INTO ORDERS (ID, AMOUNT, DESCRIPTION, ORDER_DATE, STATUS, CUSTOMER_ID)
VALUES (11, 1500, 'iPhone order', CURRENT_TIMESTAMP, 'COMPLETED', 11);

INSERT INTO ORDERS (ID, AMOUNT, DESCRIPTION, ORDER_DATE, STATUS, CUSTOMER_ID)
VALUES (12, 2500, 'Laptop order', CURRENT_TIMESTAMP, 'PENDING', 12);

-- Payments
INSERT INTO PAYMENTS (ID, ORDER_ID, AMOUNT, PAYMENT_DATE)
VALUES (11, 11, 1500, CURRENT_TIMESTAMP);
